### ISSUE TITLE
Cannot read property 'author' of undefined

### ISSUE THREAD

**Issue by cvburgess** [packtracker/test-next#11]
Using the following code with Next.js and GitHub actions in a PR.

Github actions is failing the build with the error in the title.

```js
// Deploy bundle stats to https://packtracker.io
    if (!isServer && process.env.GITHUB_EVENT_PATH) {
      const event = require(process.env.GITHUB_EVENT_PATH);
      config.plugins.push(
        new PacktrackerPlugin({
          author: event.head_commit.author.email,
          branch: event.ref.replace("refs/heads/", ""),
          commit: process.env.GITHUB_SHA,
          committed_at: parseInt(
            Number(new Date(event.head_commit.timestamp)) / 1000
          ),
          fail_build: true,
          message: event.head_commit.message,
          prior_commit: event.before,
          upload: true,
        })
      );
    }
```

Here's the complete GitHub action YAML:

```yaml
name: CI

on:
  push:
    branches: [production]
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install and cache dependencies
      - name: "Install"
        run: npm install

      # Build and bundle the react app, send stats to https://packtracker.io
      - name: "Build"
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
        run: npm run build

  Lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install and cache dependencies
      - name: "Install"
        run: npm install

      # Run linter
      - name: "Lint"
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install and cache dependencies
      - name: "Install"
        run: npm install

      # Run test suite
      - name: "Test"
        run: npm run test

```
